<div>                                                    [company_name]    </div><div>                                                                            [company_address]</div><div>                                                                           [org_fax/ph]</div><div>                        Ref : CAC/HR/APP/</div><div>                        Name : KUMAR </div><div>                        Address :               </div><div><font color="#ff0000"></font><table class="table-1"><tbody><tr bgcolor="#1c84c6"><td><font style="color: white !important;">                                                                   APPOINMENT LETTER</font></td></tr></tbody></table></div><div>Dear Sir</div><div>SUB : APPOINTMENT ORDER ON PROBATION</div><div>Please refer to your application dated 2018-06-20 and the subsequent interview, which you had with us in connection with
your appointment in our organization. In this connection we are pleased to offer you a Probationary Appointment as SHIFT
INCHARGE on the following terms and conditions.</div><div>     1. You will be on probation for a period of Six Months i.e. with effect from to . On successful and satisfactory of
which you will be considered for confirmation in your present post and            the decision of the management in this regard
is final.</div><div>     2. During the period of Probation you will be paid :</div><div>                   Basic                   :	Rs. 1080 pm</div><div>                   HRA                    :	Rs. 450 pm</div><div>                   Conveyance        :	Rs. 126 pm</div><div>                   Other Allowance :	Rs. 144 pm</div><div>                   <b>Total :	Rs. 1800 pm (Rupees Only)</b></div><div>     3. The Management at its discretion to extend your period of Probation for a further period. You will continue to be on
Probation until you are confirmed in the service of the company by a written order.</div><div>      4. During or at the expiry of the said period of probation or at the extended period of probation, the Management shall
have the right to terminate your service without any notice or assigning any reasons thereof.</div><div>     5. During the period of probation your progress, performance, attendance, timekeeping, aptitude, character and
conduct and other factors will be reviewed constantly and if at any stage these are not found to be satisfactory, your
service will be liable to be terminated without any notice or compensation in lieu of notice or assigning any reason
thereof.</div><div>     6. On confirmation your services shall be liable to be terminated on one month's notice or salary in lieu thereof except
on disciplinary grounds in which case, no such notice or payment in lieu thereof shall be necessary</div><div><div>[company_name]    </div><div>                                                                            [company_address]</div><div>                                                                           [org_fax/ph]</div><div>                        Ref : CAC/HR/APP/</div><div>                        Name : KUMAR </div><div>                        Address :    </div></div><div><table class="table-1" style="background-color: rgb(255, 255, 255); width: 1147px;"><tbody><tr bgcolor="#1c84c6"><td><font style="color: white !important;">                                                                     APPOINMENT LETTER<br></font></td></tr></tbody></table></div><div>     7. You shall not engage yourself in any other trade, business or occupation without obtaining the Management's prior
permission in writing.</div><div>     8. Your appointment and continuance in employment of the company is further subject to your being found medically
fit and company shall have the right to get you re-examined from any Registered medical practitioner as appointed
by the Management whose decision shall be final and binding.</div><div>     9. You will be liable to be transferred either on temporarily/permanently to any of our branches,factories, department
associated concerns or any other post without assigning any reason.</div><div>     10.You will be the whole-time employee of the company and shall not engage yourself in any work similar in nature to
that of the and/or in which you may for the time being be engaged by the and/or engage yourself anywhere in your
work, profession or employment either honorary or otherwise, during the period of your employment with the
company.</div><div>     11.During the tenure of your employment with us seeking employment with our competitors manufacturing similar or
allied products is totally prohibited (either by application or through personal contacts etc.). If at any time, it is
found that you violated this specific understanding and the conditions, your service will be terminated immediately
without any compensation in lieu thereof.</div><div>       12.You will be responsible for the safe keeping and return in good condition of all property of the company, which may
be given to you from time to time by the company or by any other authorized persons or persons.</div><div>       13.You shall intimate the change of your residential address if any, within three days of such change.</div><div>       14.You have to maintain strict secrecy with regard to the work entrusted to you or any other matter connected with the
Company.</div><div>       15.You will be governed by all rules and regulations as may from time to time be applicable to the Company.</div><div>       16.In the event of you're desiring to leave the services of the company for any reason, during the period of your
probation/on confirmation you shall give your intention in writing three complete calendar month in advance. It is
left to the discretion of the management to accept your resignation and relieve you within this period. In case you
given the resignation and not working the notice period we are not given the pending dues and also you have to pay
the three months' notice period amount to company. On confirmation the management can also terminate your
services by giving one month's notice in writing.</div><div>Please return the duplicate copy of this letter duly signed for having read, understood and accepted all the terms and
conditions contained in this order.</div><div>       With best wishes.</div><div>       <b>For Procandour Automotive Systems Pvt Ltd</b></div><div>ILAYARAJA.K</div><div>MANAGING DIRECTOR.</div><div>                                                                                                                                               SIGNATURE</div><div>CC: Personal File</div><div><br></div>